name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout out the repo
      uses: actions/checkout@v4
    - name: Scan the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Pull Docker Image
      run: docker pull YOUR_DOCKERHUB_USERNAME/my-custom-ubuntu  # Replace with your actual image
    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context: "."
       push: true
       tags: isimrpickle/githubaction:latest
