name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout out the repo
      uses: actions/checkout@v4
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: $isimrpickle
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context: "."
       push: true
       tags: isimrpickle/githubaction:latest #build and push this image
    - name: Scan docker image for vulnerabilities
      uses: docker/scout-action@v1 
      with:
        command: cves 
        image: isimrpickle/githubaction:latest
        platform: linux/amd64
